"""
Disaster templates used to generate realistic emergency messages.
Each category contains phrases that people may actually speak
during an emergency.
"""

# ==========================================================
# COMMON WORDS
# ==========================================================

PANIC = [
    "help",
    "please help",
    "urgent",
    "emergency",
    "save us",
    "save me",
    "quick",
    "fast",
    "please",
    "someone help",
    "need help immediately"
]

LOCATIONS = [
    "house",
    "home",
    "kitchen",
    "bedroom",
    "apartment",
    "building",
    "office",
    "school",
    "college",
    "hospital",
    "factory",
    "shop",
    "restaurant",
    "warehouse",
    "mall",
    "garage",
    "street",
    "road",
    "bus stand",
    "railway station"
]
# ==========================================================
# FIRE
# ==========================================================

FIRE_TEMPLATES = [

    "{panic}! fire in my {location}",
    "{panic}! my {location} is burning",
    "{location} caught fire",
    "heavy smoke from {location}",
    "huge flames in {location}",
    "everything is burning",
    "cannot breathe because of smoke",
    "gas cylinder exploded",
    "electrical short circuit caused fire",
    "kitchen caught fire",
    "room is filled with smoke",
    "smoke everywhere",
    "fire spreading quickly",
    "please send fire brigade",
    "our apartment is burning",
    "our office is on fire",
    "restaurant kitchen caught fire",
    "factory is burning",
    "warehouse caught fire",
    "petrol bunk caught fire",
    "forest fire nearby",
    "fire in neighbour house",
    "our ceiling is burning",
    "wire caught fire",
    "electric board caught fire",
    "AC unit caught fire",
    "transformer exploded",
    "vehicle caught fire",
    "car is burning",
    "bike is burning",
    "truck caught fire",
    "fire after explosion",
    "gas leak caused fire",
    "children trapped inside burning house",
    "people trapped inside building",
    "cannot escape because of smoke",
    "stairs blocked by fire",
    "fire reached second floor",
    "roof caught fire",
    "black smoke everywhere",
    "thick smoke coming out",
    "burning smell everywhere",
    "plastic burning smell",
    "curtains caught fire",
    "sofa caught fire",
    "bed caught fire",
    "kitchen full of smoke",
    "our shop is burning",
    "shopping mall caught fire",
    "school building caught fire",
    "hospital ward caught fire"
]
# ==========================================================
# FLOOD
# ==========================================================

FLOOD_TEMPLATES = [

    "{panic}! flood water entered our {location}",
    "{location} is completely flooded",
    "water level is rising quickly",
    "heavy rain flooded our street",
    "our house is under water",
    "we are trapped because of flood",
    "road completely submerged",
    "bridge is underwater",
    "river overflowed",
    "dam water released suddenly",
    "people stranded on rooftop",
    "need rescue boat",
    "children trapped in flood",
    "vehicles washed away",
    "cars floating in water",
    "shops flooded",
    "school surrounded by water",
    "hospital flooded",
    "our village is flooded",
    "our colony is flooded",
    "water entered ground floor",
    "water entered first floor",
    "water coming inside house",
    "cannot go outside because of flood",
    "electric poles inside flood water",
    "road disappeared under water",
    "bridge collapsed due to flood",
    "strong water current outside",
    "people waiting for rescue",
    "our belongings are floating",
    "animals trapped in flood",
    "boats needed immediately",
    "help flood everywhere",
    "rain water entering house",
    "continuous rain causing flood",
    "storm water flooded road",
    "drains overflowing",
    "sewer water mixed with flood",
    "roads blocked because of flood",
    "cannot reach hospital because of flood",
    "family trapped inside home",
    "need food and water",
    "need evacuation immediately",
    "water reached waist level",
    "water reached roof level",
    "we climbed to terrace",
    "help us rescue immediately",
    "children crying due to flood",
    "our apartment basement flooded",
    "entire area under water"
]
# ==========================================================
# EARTHQUAKE
# ==========================================================

EARTHQUAKE_TEMPLATES = [

    "{panic}! earthquake",
    "{panic}! building shaking",
    "the ground is shaking",
    "earth is moving",
    "our house is shaking",
    "building shaking badly",
    "strong earthquake felt",
    "heavy tremors felt",
    "everything is shaking",
    "walls are cracking",
    "ceiling is cracking",
    "glass windows broke",
    "furniture shaking",
    "fan shaking violently",
    "people running outside",
    "everyone is panicking",
    "our apartment is shaking",
    "office building shaking",
    "school building shaking",
    "hospital building shaking",
    "earthquake just happened",
    "aftershock happened",
    "strong vibrations everywhere",
    "roof is cracking",
    "stairs are damaged",
    "building may collapse",
    "cracks appeared on wall",
    "floor is vibrating",
    "door is shaking",
    "lights are swinging",
    "objects falling down",
    "television fell down",
    "cupboard fell",
    "books falling from shelf",
    "cannot stand properly",
    "our building is unsafe",
    "people trapped after earthquake",
    "bridge damaged after earthquake",
    "road cracked after earthquake",
    "house developed huge cracks",
    "building tilted slightly",
    "everyone evacuated building",
    "need rescue after earthquake",
    "help building may collapse",
    "the whole area is shaking",
    "it feels like an earthquake",
    "earth moving continuously",
    "please send rescue teams",
    "many people are injured",
    "debris everywhere"
]
# ==========================================================
# MEDICAL EMERGENCY
# ==========================================================

MEDICAL_TEMPLATES = [

    "{panic}! need ambulance",
    "{panic}! medical emergency",
    "my father fainted",
    "my mother collapsed",
    "someone is unconscious",
    "patient is not responding",
    "person is not breathing",
    "difficulty in breathing",
    "severe chest pain",
    "possible heart attack",
    "possible stroke",
    "heavy bleeding",
    "head injury after fall",
    "person had a seizure",
    "high fever and unconscious",
    "child is unconscious",
    "elderly person collapsed",
    "woman fainted suddenly",
    "person is choking",
    "cannot breathe properly",
    "need oxygen immediately",
    "need ambulance urgently",
    "patient is bleeding heavily",
    "accident victim needs medical help",
    "burn injuries need treatment",
    "snake bite emergency",
    "dog bite emergency",
    "food poisoning suspected",
    "medicine overdose",
    "person swallowed poison",
    "severe allergic reaction",
    "uncontrolled vomiting",
    "person having severe pain",
    "broken leg after fall",
    "broken arm after accident",
    "serious head injury",
    "patient lost consciousness",
    "heart patient collapsed",
    "diabetic patient unconscious",
    "blood pressure very low",
    "patient cannot walk",
    "patient unable to speak",
    "person trapped and injured",
    "need first aid immediately",
    "ambulance has not arrived",
    "please send medical team",
    "need emergency doctor",
    "multiple injured people",
    "critical medical emergency",
    "save the patient"
]
# ==========================================================
# STORM / CYCLONE
# ==========================================================

STORM_TEMPLATES = [

    "{panic}! cyclone approaching",
    "{panic}! heavy storm",
    "very strong winds outside",
    "cyclone has reached our area",
    "roof flew away",
    "tree fell on our house",
    "tree blocking the road",
    "electric poles have fallen",
    "power lines are down",
    "heavy rain with strong winds",
    "storm damaged our house",
    "windows shattered due to wind",
    "doors are shaking violently",
    "roof is collapsing",
    "houses damaged by cyclone",
    "roads blocked by fallen trees",
    "cars damaged by trees",
    "people trapped after storm",
    "flying debris everywhere",
    "storm destroyed our shop",
    "our village is badly affected",
    "telephone poles collapsed",
    "internet cables snapped",
    "electricity gone after cyclone",
    "trees uprooted everywhere",
    "bridge damaged by storm",
    "need rescue after cyclone",
    "storm water entered house",
    "storm becoming stronger",
    "cannot leave home because of storm",
    "hailstorm damaged vehicles",
    "heavy rain and thunderstorm",
    "lightning struck nearby",
    "house flooded during cyclone",
    "roof leaking badly",
    "building damaged by wind",
    "help us after cyclone",
    "roads completely blocked",
    "our area has no electricity",
    "communication lost after storm",
    "everyone is scared",
    "need emergency shelter",
    "please send rescue teams",
    "many houses destroyed",
    "storm is getting worse",
    "trees falling continuously",
    "high speed winds everywhere",
    "cyclone warning issued",
    "people evacuated from village",
    "emergency due to cyclone"
]
# ==========================================================
# GAS LEAK
# ==========================================================

GAS_LEAK_TEMPLATES = [

    "{panic}! gas leak in the kitchen",
    "{panic}! strong gas smell",
    "gas cylinder is leaking",
    "lpg gas leak",
    "gas is coming from the stove",
    "strong smell of gas inside house",
    "cannot stay inside because of gas smell",
    "hissing sound from gas cylinder",
    "gas pipe is leaking",
    "gas regulator is leaking",
    "kitchen filled with gas smell",
    "gas leakage detected",
    "possible gas leak",
    "please send emergency team",
    "cylinder valve is leaking",
    "gas smell everywhere",
    "gas leak near restaurant",
    "gas leak in apartment",
    "gas leak in office pantry",
    "chemical smell inside building",
    "people feeling dizzy because of gas",
    "difficulty breathing due to gas",
    "gas leak after cylinder burst",
    "flammable gas leaking",
    "do not know where gas is leaking",
    "strong lpg smell from kitchen",
    "gas leaking continuously",
    "need help gas leak",
    "emergency gas leak",
    "kitchen unsafe because of gas",
    "gas leak near hospital",
    "gas leak in factory",
    "industrial gas leak",
    "toxic gas smell",
    "children inside during gas leak",
    "gas leaking from pipeline",
    "dangerous gas smell",
    "gas spreading throughout house",
    "everyone evacuated because of gas",
    "possible explosion due to gas",
    "gas leak near warehouse",
    "residents evacuated due to gas",
    "suspected gas cylinder failure",
    "gas smell becoming stronger",
    "need immediate assistance",
    "cannot stop the gas leak",
    "gas alarm is ringing",
    "gas detected in basement",
    "help us before explosion",
    "gas emergency"
]
# ==========================================================
# BUILDING COLLAPSE
# ==========================================================

BUILDING_COLLAPSE_TEMPLATES = [

    "{panic}! building collapsed",
    "{panic}! house collapsed",
    "our building has collapsed",
    "part of the building collapsed",
    "roof collapsed suddenly",
    "ceiling collapsed",
    "wall collapsed",
    "staircase collapsed",
    "apartment building collapsed",
    "office building collapsed",
    "shopping mall collapsed",
    "school building collapsed",
    "old building collapsed",
    "building cracking badly",
    "building about to collapse",
    "huge cracks in the building",
    "roof is falling down",
    "ceiling is falling",
    "walls have huge cracks",
    "our house is breaking apart",
    "people trapped under debris",
    "children trapped under collapsed building",
    "family trapped inside collapsed house",
    "cannot come out because building collapsed",
    "rescue team needed immediately",
    "many people injured after collapse",
    "building collapsed after earthquake",
    "building collapsed after heavy rain",
    "construction building collapsed",
    "bridge partially collapsed",
    "balcony collapsed",
    "lift trapped after collapse",
    "main entrance blocked by debris",
    "concrete fell from roof",
    "bricks falling from wall",
    "our building is unsafe",
    "danger of complete collapse",
    "building shaking and collapsing",
    "need rescue urgently",
    "help people trapped",
    "debris everywhere",
    "dust everywhere after collapse",
    "cannot reach trapped people",
    "road blocked by collapsed building",
    "house destroyed completely",
    "emergency building collapse",
    "many residents trapped",
    "collapsed structure blocking road",
    "building failure occurred",
    "building disaster"
]
# ==========================================================
# ROAD ACCIDENT
# ==========================================================

ROAD_ACCIDENT_TEMPLATES = [

    "{panic}! road accident",
    "{panic}! major accident",
    "car accident on the highway",
    "bike accident near the junction",
    "truck collided with a bus",
    "two cars crashed",
    "vehicle overturned",
    "car hit a tree",
    "bus accident",
    "lorry accident",
    "multiple vehicles collided",
    "serious road accident",
    "accident near traffic signal",
    "accident on bridge",
    "accident near railway crossing",
    "person hit by a car",
    "pedestrian injured",
    "cyclist hit by vehicle",
    "people trapped inside car",
    "driver unconscious after accident",
    "passengers injured",
    "heavy bleeding after accident",
    "need ambulance after accident",
    "road completely blocked",
    "traffic stopped because of accident",
    "fuel leaking from vehicle",
    "vehicle caught fire after crash",
    "glass shattered everywhere",
    "car rolled over",
    "bike skid on road",
    "truck lost control",
    "head-on collision",
    "high-speed accident",
    "car fell into ditch",
    "bus fell into canal",
    "accident due to heavy rain",
    "accident due to fog",
    "person trapped under vehicle",
    "rescue team required",
    "ambulance needed immediately",
    "driver seriously injured",
    "children injured in accident",
    "road full of damaged vehicles",
    "cannot move the injured",
    "accident happened just now",
    "help accident victims",
    "major collision",
    "emergency road accident",
    "several people injured",
    "save the accident victims"
]
# ==========================================================
# LANDSLIDE
# ==========================================================

LANDSLIDE_TEMPLATES = [

    "{panic}! landslide",
    "huge landslide occurred",
    "rocks falling from hill",
    "mudslide blocking road",
    "road blocked by landslide",
    "mountain collapsed",
    "soil sliding downhill",
    "houses buried in mud",
    "people trapped after landslide",
    "trees buried in landslide",
    "vehicles trapped under rocks",
    "bridge damaged by landslide",
    "heavy rain caused landslide",
    "village affected by landslide",
    "cannot cross because of landslide",
    "road completely blocked",
    "rocks covering highway",
    "landslide near tunnel",
    "mud entered our house",
    "need rescue after landslide",
    "family trapped in landslide",
    "houses damaged by falling rocks",
    "danger of another landslide",
    "continuous soil movement",
    "mountain road collapsed",
    "emergency landslide",
    "people missing after landslide",
    "help us landslide",
    "many vehicles stranded",
    "large rocks on road",
    "hill collapsing",
    "earth sliding down",
    "mud everywhere",
    "road disappeared due to landslide",
    "dangerous hillside movement",
    "heavy debris blocking road",
    "cannot reach village",
    "rescue teams required",
    "people injured in landslide",
    "landslide getting worse",
    "houses collapsing due to landslide",
    "road washed away",
    "bridge inaccessible",
    "save trapped people",
    "mountain disaster",
    "need immediate evacuation",
    "landslide after heavy rainfall",
    "huge boulders on road",
    "residents trapped",
    "natural disaster landslide"
]
# ==========================================================
# ELECTRICAL HAZARD
# ==========================================================

ELECTRICAL_HAZARD_TEMPLATES = [

    "{panic}! electric shock",
    "{panic}! current leakage",
    "live wire on the road",
    "electric pole has fallen",
    "power line snapped",
    "high voltage wire down",
    "wire sparking",
    "electric short circuit",
    "switchboard caught fire",
    "transformer exploded",
    "electric meter burning",
    "current coming through water",
    "wire touching the ground",
    "dangerous electric sparks",
    "electricity leaking",
    "power cable broken",
    "person received electric shock",
    "child touched live wire",
    "live cable exposed",
    "water near electric wire",
    "pole may fall",
    "burning smell from switchboard",
    "electric panel smoking",
    "generator caught fire",
    "high voltage danger",
    "power outage after explosion",
    "people trapped near live wire",
    "do not know where current is coming from",
    "electric wire fell on vehicle",
    "transformer making loud noise",
    "electrical fire started",
    "current passing through gate",
    "touching gate gives shock",
    "house wiring problem",
    "office electrical emergency",
    "factory electrical accident",
    "need electricity department",
    "danger due to exposed wire",
    "sparks everywhere",
    "electric hazard",
    "power line broken",
    "electrical emergency",
    "immediate electrical assistance needed",
    "high voltage emergency",
    "help electric shock",
    "live wire near school",
    "live wire near hospital",
    "electrical accident occurred",
    "people injured by electric shock",
    "electrical disaster"
]